name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  commits:
    name: commits
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: webiny/action-conventional-commits@v1.3.0

  linter:
    name: linter
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Download checkpatch
        run: wget https://raw.githubusercontent.com/torvalds/linux/master/scripts/checkpatch.pl

      - name: Make checkpatch executable
        run: chmod +x checkpatch.pl

      - name: Run checkpatch
        run: ./checkpatch.pl --no-tree --terse --show-types -f *.c --ignore FILE_PATH_CHANGES --ignore LONG_LINE --ignore LONG_LINE_STRING --ignore LONG_LINE_COMMENT --ignore LONG_LINE_STRING --ignore LONG_LINE_COMMENT --ignore LONG_LINE_COMMENT

  build:
    name: build
    runs-on: ubuntu-latest
    needs: linter

    steps:
      - uses: actions/checkout@v4

      - name: Update sources
        run: sudo apt update

      - name: Install dependencies
        run: sudo apt install -y build-essential linux-sources-$(uname -r) kmod dwarves

      - name: Build project
        run: make

      - name: Clean project
        run: make clean
