name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  commits:
    name: commits
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: webiny/action-conventional-commits@v1.3.0

  linter:
    name: linter
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: otp

    steps:
      - uses: actions/checkout@v4

      - name: Download checkpatch
        run: wget https://raw.githubusercontent.com/torvalds/linux/master/scripts/checkpatch.pl

      - name: Make checkpatch executable
        run: chmod +x checkpatch.pl

      - name: Run checkpatch
        run: ./checkpatch.pl --no-tree --terse --show-types -f *.c --ignore FILE_PATH_CHANGES --ignore LONG_LINE --ignore LONG_LINE_STRING --ignore LONG_LINE_COMMENT --ignore LONG_LINE_STRING --ignore LONG_LINE_COMMENT --ignore LONG_LINE_COMMENT

  build_otp_module:
    name: build OTP module
    runs-on: ubuntu-latest
    needs: linter
    defaults:
      run:
        working-directory: otp

    steps:
      - uses: actions/checkout@v4

      - name: Create builder image
        run: docker build . -t kernel_builder

      - name: Build project
        run: >
          docker run --rm
          -v ${{ github.workspace }}/otp:/build
          kernel_builder
          make

      - name: Clean project
        run: >
          docker run --rm
          -v ${{ github.workspace }}/otp:/build
          kernel_builder
          make clean

  build_otp_tools:
    name: build OTP tools
    runs-on: ubuntu-latest
    needs: build_otp_module
    defaults:
      run:
        working-directory: otp_tools

    steps:
      - uses: actions/checkout@v4

      - name: Build OTP tools
        run: cargo build --release
